fix package so it installs on worker nodes

diff --git a/python-oq/debian/postinst b/python-oq/debian/postinst
--- a/python-oq/debian/postinst
+++ b/python-oq/debian/postinst
@@ -19,18 +19,20 @@ set -e
 # the debian-policy package
 
 
-# create rabbitmq configuration for python-celery
-celeryuser_count=`rabbitmqctl list_users | grep celeryuser | wc -l`
-if [ $celeryuser_count -eq 0 ];
-then
-    rabbitmqctl add_user celeryuser celery
-fi;
-celeryvhost_count=`rabbitmqctl list_vhosts | grep celeryvhost | wc -l`
-if [ $celeryvhost_count -eq 0 ];
-then
-    rabbitmqctl add_vhost celeryvhost
-    rabbitmqctl set_permissions -p celeryvhost celeryuser ".*" ".*" ".*"
-fi;
+if [ -f /usr/sbin/rabbitmqctl ]; then
+    # create rabbitmq configuration for python-celery
+    celeryuser_count=`rabbitmqctl list_users | grep celeryuser | wc -l`
+    if [ $celeryuser_count -eq 0 ];
+    then
+        rabbitmqctl add_user celeryuser celery
+    fi;
+    celeryvhost_count=`rabbitmqctl list_vhosts | grep celeryvhost | wc -l`
+    if [ $celeryvhost_count -eq 0 ];
+    then
+        rabbitmqctl add_vhost celeryvhost
+        rabbitmqctl set_permissions -p celeryvhost celeryuser ".*" ".*" ".*"
+    fi;
+fi
 
 mkdir -p /usr/openquake
 chmod 1777 /usr/openquake
@@ -59,40 +61,37 @@ do
 done
 
 # Is postgres installed on this system?
-if ! dpkg-query -l postgresql-8.4 >/dev/null; then
-    echo "No postgresql package installed"
-    exit 2
+if [ -f /usr/lib/postgresql/8.4/bin/postgres ]; then
+    # postgres is installed, flatten and recreate the database.
+    LOGFILE=/var/tmp/openquake-db-installation
+    rm -f $LOGFILE
+    su -c "/usr/bin/oq_create_db --yes --db-name=openquake --schema-path=$IDIR/db/schema > $LOGFILE 2>&1" postgres
+    for dbu in oq_admin oq_job_init oq_job_superv oq_reslt_writer
+    do
+        su -c "psql -c \"ALTER ROLE $dbu WITH PASSWORD 'openquake'\" >> $LOGFILE 2>&1" postgres
+    done
+    chmod 644 $LOGFILE
+
+    num_of_errors=`grep -i error $LOGFILE | grep -v "is not empty" | grep -v error_msg_ | wc -l`
+    if [ $num_of_errors -gt 0 ]; then
+        echo "Failed to initialise the openquake database"
+        echo "Please file a bug here:"
+        echo "    https://bugs.launchpad.net/openquake/+filebug"
+        echo "and attach this file to it:"
+        echo "    $LOGFILE"
+        su -c "psql -c \"DROP DATABASE openquake\" >/dev/null 2>&1" postgres
+        exit 1
+    fi
+
+    PG_ROOT=/etc/postgresql/8.4/main
+    cp $PG_ROOT/pg_hba.conf $PG_ROOT/pg_hba.conf.orig
+    for dbu in oq_admin oq_job_init oq_job_superv oq_reslt_writer
+    do
+        echo "local   openquake   $dbu                   md5" > $PG_ROOT/pg_hba.conf
+    done
+    cat $PG_ROOT/pg_hba.conf.orig | grep -v oq_ >> $PG_ROOT/pg_hba.conf
+    /etc/init.d/postgresql reload
 fi
-
-# postgres is installed, flatten and recreate the database.
-LOGFILE=/var/tmp/openquake-db-installation
-rm -f $LOGFILE
-su -c "/usr/bin/oq_create_db --yes --db-name=openquake --schema-path=$IDIR/db/schema > $LOGFILE 2>&1" postgres
-for dbu in oq_admin oq_job_init oq_job_superv oq_reslt_writer
-do
-    su -c "psql -c \"ALTER ROLE $dbu WITH PASSWORD 'openquake'\" >> $LOGFILE 2>&1" postgres
-done
-chmod 644 $LOGFILE
-
-num_of_errors=`grep -i error $LOGFILE | grep -v "is not empty" | grep -v error_msg_ | wc -l`
-if [ $num_of_errors -gt 0 ]; then
-    echo "Failed to initialise the openquake database"
-    echo "Please file a bug here:"
-    echo "    https://bugs.launchpad.net/openquake/+filebug"
-    echo "and attach this file to it:"
-    echo "    $LOGFILE"
-    su -c "psql -c \"DROP DATABASE openquake\" >/dev/null 2>&1" postgres
-    exit 1
-fi
-
-PG_ROOT=/etc/postgresql/8.4/main
-cp $PG_ROOT/pg_hba.conf $PG_ROOT/pg_hba.conf.orig
-for dbu in oq_admin oq_job_init oq_job_superv oq_reslt_writer
-do
-    echo "local   openquake   $dbu                   md5" > $PG_ROOT/pg_hba.conf
-done
-cat $PG_ROOT/pg_hba.conf.orig | grep -v oq_ >> $PG_ROOT/pg_hba.conf
-/etc/init.d/postgresql reload
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
