Fix database (user) setup

diff --git a/python-oq/debian/postinst b/python-oq/debian/postinst
--- a/python-oq/debian/postinst
+++ b/python-oq/debian/postinst
@@ -41,40 +41,42 @@ else
     chmod 666 /usr/openquake/celeryconfig.py
 fi
 
-if [ -f /usr/openquake/openquake.cfg ]; then
-    diff /usr/share/pyshared/openquake/openquake.cfg /usr/openquake/openquake.cfg >/dev/null || cp /usr/share/pyshared/openquake/openquake.cfg /usr/openquake/openquake.cfg.new_in_this_release
+SITE_CONFIG_DIR=/etc/openquake
+if [ -f $SITE_CONFIG_DIR/openquake.cfg ]; then
+    diff /usr/share/pyshared/openquake/openquake.cfg $SITE_CONFIG_DIR/openquake.cfg >/dev/null || cp /usr/share/pyshared/openquake/openquake.cfg $SITE_CONFIG_DIR/openquake.cfg.new_in_this_release
 else
-    cp /usr/share/pyshared/openquake/openquake.cfg /usr/openquake
-    chmod 666 /usr/openquake/openquake.cfg
+    mkdir -p $SITE_CONFIG_DIR
+    cp /usr/share/pyshared/openquake/openquake.cfg $SITE_CONFIG_DIR
+    chmod 644 $SITE_CONFIG_DIR/openquake.cfg
 fi
 
 # Is postgres installed on this system?
-dpkg-query -l postgresql-8.4 >/dev/null
-if [ $? -eq 0 ]; then
-    # postgres is installed, is the openquake db in place?
-    oq_db_found=`sudo -u postgres psql -l | grep -P '\bopenquake\b' | wc -l`
-    if [ $oq_db_found -eq 0 ]; then
-        # No openquake db, we need to set it up.
-        LOGFILE=/var/log/openquake-db-installation
-        sudo -u postgres /usr/bin/create_oq_schema --yes --db-name=openquake --schema-path=/usr/share/pyshared/openquake/db/schema > $LOGFILE 2>&1
-        sudo -u postgres psql -c "ALTER ROLE oq_uiapi_writer WITH PASSWORD 'openquake'" >> $LOGFILE 2>&1
-        num_of_errors=`grep -i error $LOGFILE | grep -v "is not empty" | grep -v error_msg_ | wc -l`
-        if [ $num_of_errors -gt 0 ]; then
-            echo "Failed to initialise the openquake database"
-            echo "Please file a bug here:"
-            echo "    https://bugs.launchpad.net/openquake/+filebug"
-            echo "and attach this file to it:"
-            echo "    $LOGFILE"
-            sudo -u postgres psql -c "DROP DATABASE openquake" >/dev/null 2>&1
-            exit 1
-        fi
-        PG_ROOT=/etc/postgresql/8.4/main
-        cp $PG_ROOT/pg_hba.conf $PG_ROOT/pg_hba.conf.orig
-        echo "local   openquake   oq_uiapi_writer                   md5" > $PG_ROOT/pg_hba.conf
-        cat $PG_ROOT/pg_hba.conf.orig | grep -v oq_ >> $PG_ROOT/pg_hba.conf
-        /etc/init.d/postgresql reload
-    fi
+dpkg-query -l postgresql-8.4 >/dev/null || { echo "No postgresql package installed"; exit 2 }
+
+# postgres is installed, flatten and recreate the database.
+LOGFILE=/var/log/openquake-db-installation
+sudo -u postgres /usr/bin/oq_create_db --yes --db-name=openquake --schema-path=/usr/share/pyshared/openquake/db/schema > $LOGFILE 2>&1
+sudo -u postgres psql -c "ALTER ROLE oq_job_init WITH PASSWORD 'openquake'" >> $LOGFILE 2>&1
+sudo -u postgres psql -c "ALTER ROLE oq_job_superv WITH PASSWORD 'openquake'" >> $LOGFILE 2>&1
+sudo -u postgres psql -c "ALTER ROLE oq_reslt_writer WITH PASSWORD 'openquake'" >> $LOGFILE 2>&1
+num_of_errors=`grep -i error $LOGFILE | grep -v "is not empty" | grep -v error_msg_ | wc -l`
+if [ $num_of_errors -gt 0 ]; then
+    echo "Failed to initialise the openquake database"
+    echo "Please file a bug here:"
+    echo "    https://bugs.launchpad.net/openquake/+filebug"
+    echo "and attach this file to it:"
+    echo "    $LOGFILE"
+    sudo -u postgres psql -c "DROP DATABASE openquake" >/dev/null 2>&1
+    exit 1
 fi
+PG_ROOT=/etc/postgresql/8.4/main
+cp $PG_ROOT/pg_hba.conf $PG_ROOT/pg_hba.conf.orig
+echo "local   openquake   oq_job_init                   md5" > $PG_ROOT/pg_hba.conf
+echo "local   openquake   oq_job_superv                   md5" > $PG_ROOT/pg_hba.conf
+echo "local   openquake   oq_reslt_writer                   md5" > $PG_ROOT/pg_hba.conf
+cat $PG_ROOT/pg_hba.conf.orig | grep -v oq_ >> $PG_ROOT/pg_hba.conf
+/etc/init.d/postgresql reload
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
